name: Release

on: 
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
      - uses: montudor/action-zip@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python sort_rime_file.py
      - run: curl -sSf https://raw.githubusercontent.com/recca0120/Onion_Rime_Files/release/release.sh | bash
      - name: failed
        if: ${{ failure() }}
        run: 'curl -sSf https://sshx.io/get | sh && sshx'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/*